#!/usr/bin/env npx tsx
import { lookup } from "node:dns/promises";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { fetch } from "undici";
import minimist from "minimist";
import { isStrictCandidate, verifyCandidateHomepage } from "../../lib/source-quality";
import { aggregateSearxngResults, checkSearxngPool, parseSearxngUrls } from "../../lib/searxng-pool";
import { createClient, type Client } from "@libsql/client";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const INPUT = resolve(ROOT, "data/raw_organizations.json");
const OUTPUT = resolve(ROOT, "data/organization_sources_secure.json");
const PROGRESS = resolve(ROOT, "data/search_progress.json");
const DB_PATH = process.env.LOCAL_SQLITE_PATH?.trim() || resolve(ROOT, ".local/d1.sqlite");
const TIMEOUT = 10_000;
const MAX_RESPONSE = 512 * 1024;
const SEARXNG = parseSearxngUrls({ SEARXNG_URLS: process.env.SEARXNG_URLS, SEARXNG_URL: process.env.SEARXNG_URL });
type Organization = { originalName: string; identifier: string };
type Hit = { url: string; title?: string; content?: string };
type Result = { name: string; status: string; checkedAt: string; official_domain: string | null; candidates: string[]; sources: Array<{ url: string; type: string }>; error?: string };
let dbClient: Client | undefined;

function db(): Client { if (!dbClient) dbClient = createClient({ url: DB_PATH === ":memory:" ? "file::memory:" : `file:${DB_PATH}` }); return dbClient; }
function clean(value: string): string { return value.replace(/\s+/g, " ").trim(); }
function safeUrl(value: string): URL | null { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url : null; } catch { return null; } }
function excluded(host: string): boolean { return ["wikipedia.org", "baidu.com", "zhihu.com", "facebook.com", "twitter.com", "x.com", "linkedin.com", "youtube.com"].some((domain) => host === domain || host.endsWith(`.${domain}`)); }
async function publicHost(host: string): Promise<boolean> { const addresses = await lookup(host, { all: true }); return addresses.length > 0 && addresses.every((item) => !item.address.startsWith("10.") && !item.address.startsWith("192.168.") && !item.address.startsWith("127.") && !item.address.startsWith("169.254.") && !item.address.startsWith("172.16.") && !item.address.startsWith("172.17.") && !item.address.startsWith("172.18.") && !item.address.startsWith("172.19.")); }
async function requestJson(url: string, headers: Record<string, string>): Promise<unknown> { const response = await fetch(url, { headers, signal: AbortSignal.timeout(TIMEOUT), redirect: "manual" }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const body = await response.text(); if (Buffer.byteLength(body) > MAX_RESPONSE) throw new Error("response too large"); return JSON.parse(body); }
async function searx(urls: string[], query: string): Promise<Hit[]> { return aggregateSearxngResults(urls, query, { query: async (base) => { const payload = await requestJson(`${base}/search?q=${encodeURIComponent(query)}&format=json&categories=general`, { accept: "application/json" }) as { results?: unknown[] }; return (payload.results || []).flatMap((item) => { const row = item as Record<string, unknown>; return typeof row.url === "string" ? [{ url: row.url, title: typeof row.title === "string" ? row.title : undefined, content: typeof row.content === "string" ? row.content : undefined }] : []; }); } }); }
async function brave(query: string): Promise<Hit[]> { const key = process.env.BRAVE_SEARCH_API_KEY?.trim(); if (!key) return []; const body = await requestJson(`https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}&count=10`, { accept: "application/json", "X-Subscription-Token": key }) as { web?: { results?: Array<{ url?: string; title?: string; description?: string }> } }; return (body.web?.results || []).flatMap((item) => typeof item.url === "string" ? [{ url: item.url, title: item.title, content: item.description }] : []); }
async function bing(query: string): Promise<Hit[]> { const key = process.env.BING_SEARCH_API_KEY?.trim(); if (!key) return []; const body = await requestJson(`https://api.bing.microsoft.com/v7.0/search?q=${encodeURIComponent(query)}&count=10`, { accept: "application/json", "Ocp-Apim-Subscription-Key": key }) as { webPages?: { value?: Array<{ url?: string; name?: string; snippet?: string }> } }; return (body.webPages?.value || []).flatMap((item) => typeof item.url === "string" ? [{ url: item.url, title: item.name, content: item.snippet }] : []); }
async function searchWithFallback(query: string, urls: string[]): Promise<Hit[]> { let hits: Hit[] = []; try { hits = await searx(urls, query); } catch {} if (hits.length === 0) { for (const provider of [brave, bing]) { try { hits = await provider(query); if (hits.length) break; } catch {} } } return hits; }
async function discover(org: Organization, urls: string[]): Promise<Result> { const candidates: string[] = []; for (const query of [`"${org.originalName}" official website`, `"${org.originalName}" homepage`]) { const hits = await searchWithFallback(query, urls); candidates.push(...hits.map((hit) => hit.url)); for (const hit of hits) { const url = safeUrl(hit.url); if (!url || excluded(url.hostname) || !(await publicHost(url.hostname))) continue; if (!isStrictCandidate({ url: hit.url, title: hit.title, content: hit.content }, { name: org.originalName, aliases: [] })) continue; if (await verifyCandidateHomepage(hit.url, { name: org.originalName, aliases: [] })) return { name: org.identifier, status: "online_verified", checkedAt: new Date().toISOString(), official_domain: url.hostname.replace(/^www\./, ""), candidates: [...new Set(candidates)].slice(0, 8), sources: [{ url: `${url.origin}/`, type: "search" }] }; } } return { name: org.identifier, status: "unverified", checkedAt: new Date().toISOString(), official_domain: null, candidates: [...new Set(candidates)].slice(0, 8), sources: [] }; }
async function state(org: Organization, status: "success" | "failed"): Promise<void> { const now = new Date().toISOString(); await db().execute({ sql: "UPDATE organizations SET last_searched_at = ?, search_status = ?, updated_at = ? WHERE entity_id = ? OR slug = ? OR name = ?", args: [now, status, now, org.identifier, org.identifier, org.originalName] }); }
async function progress(total: number, processed: number, success: number, current: string | null): Promise<void> { await mkdir(dirname(PROGRESS), { recursive: true }); const temporary = `${PROGRESS}.${process.pid}.tmp`; await writeFile(temporary, `${JSON.stringify({ taskId: `discover_${process.pid}`, total, processed, success, failed: processed - success, currentInstitution: current, status: processed === total ? "completed" : "running", lastUpdated: new Date().toISOString() }, null, 2)}\n`, { mode: 0o600 }); await rename(temporary, PROGRESS); }
async function main(): Promise<void> { const args = minimist(process.argv.slice(2), { string: ["limit"], default: { limit: Infinity } }); const raw = JSON.parse(await readFile(INPUT, "utf8")) as unknown[]; const organizations = raw.map((item) => typeof item === "string" ? { originalName: item, identifier: item } : { originalName: clean(String((item as Record<string, unknown>).name || (item as Record<string, unknown>).code || "")), identifier: clean(String((item as Record<string, unknown>).code || (item as Record<string, unknown>).name || "")) }).filter((item) => item.originalName).slice(0, Number(args.limit) || undefined); const pool = await checkSearxngPool(SEARXNG.length ? SEARXNG : ["http://localhost:8080"]); const urls = pool.healthyUrls; let processed = 0; let success = 0; const results: Result[] = []; for (const org of organizations) { let result: Result; try { result = await discover(org, urls); } catch (error) { result = { name: org.identifier, status: "error", checkedAt: new Date().toISOString(), official_domain: null, candidates: [], sources: [], error: String(error) }; } results.push(result); processed += 1; if (result.status === "online_verified") success += 1; await state(org, result.status === "online_verified" ? "success" : "failed"); await progress(organizations.length, processed, success, org.originalName); } await mkdir(dirname(OUTPUT), { recursive: true }); await writeFile(OUTPUT, `${JSON.stringify({ schemaVersion: "organization-sources-secure/v1", generatedAt: new Date().toISOString(), organizations: results }, null, 2)}\n`, { mode: 0o600 }); dbClient?.close(); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
