#!/usr/bin/env npx tsx
import { lookup } from "node:dns/promises";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { cancelResponseBody, createLimiter, fetchControlled, logActiveSockets } from "../../lib/http-control";
// @ts-expect-error minimist 1.x does not ship TypeScript declarations.
import minimist from "minimist";
import { verifyCandidateHomepage } from "../../lib/source-quality";
import { aggregateSearxngResults, checkSearxngPool, parseSearxngUrls } from "../../lib/searxng-pool";
import { createClient, type Client } from "@libsql/client";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const INPUT = resolve(ROOT, "data/raw_organizations.json");
const OUTPUT = resolve(ROOT, "data/organization_sources_secure.json");
const PROGRESS = resolve(ROOT, "data/search_progress.json");
const WHITELIST = resolve(ROOT, "data/known_domains_whitelist.json");
const DB_PATH = process.env.LOCAL_SQLITE_PATH?.trim() || resolve(ROOT, ".local/d1.sqlite");
const envInt = (name: string, fallback: number): number => {
  const value = Number(process.env[name]);
  return Number.isInteger(value) && value > 0 ? value : fallback;
};
const TIMEOUT = envInt("DISCOVERY_TIMEOUT_MS", 10_000);
const MAX_RESPONSE = envInt("DISCOVERY_MAX_RESPONSE_BYTES", 512 * 1024);
const SEARXNG = parseSearxngUrls({ SEARXNG_URLS: process.env.SEARXNG_URLS, SEARXNG_URL: process.env.SEARXNG_URL });
const DEFAULT_SEARXNG_ENGINES = ["google", "bing", "duckduckgo", "baidu", "startpage", "qwant"];
const SEARXNG_ENGINES = [...new Set((process.env.SEARXNG_ENGINES || DEFAULT_SEARXNG_ENGINES.join(",")).split(",").map((value) => value.trim()).filter(Boolean))];
type Organization = { originalName: string; identifier: string };
type Hit = { url: string; title?: string; content?: string };
type Result = { name: string; status: string; checkedAt: string; official_domain: string | null; candidates: string[]; sources: Array<{ url: string; type: string }>; error?: string };
type WhitelistEntry = { name?: string; code?: string; aliases: string[]; officialDomain: string };
let dbClient: Client | undefined;
let warnedBraveKey = false;
let warnedBingKey = false;
let warnedFallbackKeys = false;
const searxLimiter = createLimiter(envInt("SEARXNG_CONCURRENCY", 8));
const homepageLimiter = createLimiter(envInt("HOMEPAGE_CONCURRENCY", 4));

function db(): Client { if (!dbClient) dbClient = createClient({ url: DB_PATH === ":memory:" ? "file::memory:" : `file:${DB_PATH}` }); return dbClient; }
function clean(value: string): string { return value.replace(/\s+/g, " ").trim(); }
function normalize(value: string): string { return clean(value).toLocaleLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, ""); }
function safeUrl(value: string): URL | null { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url : null; } catch { return null; } }
function excluded(host: string): boolean { return ["wikipedia.org", "baidu.com", "zhihu.com", "facebook.com", "twitter.com", "x.com", "linkedin.com", "youtube.com"].some((domain) => host === domain || host.endsWith(`.${domain}`)); }
async function publicHost(host: string): Promise<boolean> { const addresses = await lookup(host, { all: true }); return addresses.length > 0 && addresses.every((item) => !item.address.startsWith("10.") && !item.address.startsWith("192.168.") && !item.address.startsWith("127.") && !item.address.startsWith("169.254.") && !item.address.startsWith("172.16.") && !item.address.startsWith("172.17.") && !item.address.startsWith("172.18.") && !item.address.startsWith("172.19.")); }
class HttpError extends Error { constructor(public readonly status: number, message: string) { super(message); this.name = "HttpError"; } }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
async function requestJson(url: string, headers: Record<string, string>): Promise<unknown> { let response: Response | undefined; try { response = await fetchControlled(url, { headers, redirect: "manual" }, TIMEOUT); if (!response.ok) throw new HttpError(response.status, `HTTP ${response.status}`); const body = await response.text(); if (Buffer.byteLength(body) > MAX_RESPONSE) throw new Error("response too large"); return JSON.parse(body); } finally { if (response) await cancelResponseBody(response); } }
async function searx(urls: string[], query: string): Promise<Hit[]> { return aggregateSearxngResults(urls, query, { query: (base) => searxLimiter.run(async () => { const params = new URLSearchParams({ q: query, format: "json", categories: "general", engines: SEARXNG_ENGINES.join(",") }); const fallbackParams = new URLSearchParams({ q: query, format: "json", categories: "general" }); let payload: { results?: unknown[] }; try { payload = await requestJson(`${base}/search?${params}`, { accept: "application/json" }) as { results?: unknown[] }; } catch (error) { const status = error instanceof HttpError ? ` HTTP状态码=${error.status}` : ""; console.warn(`[SearXNG] 请求失败（带 engines=${SEARXNG_ENGINES.join(",")}）: ${errorMessage(error)}${status}`); try { payload = await requestJson(`${base}/search?${fallbackParams}`, { accept: "application/json" }) as { results?: unknown[] }; console.log(`[SearXNG] 已使用不带 engines 参数的兼容请求: ${base}`); } catch (fallbackError) { const fallbackStatus = fallbackError instanceof HttpError ? ` HTTP状态码=${fallbackError.status}` : ""; console.error(`[SearXNG] 兼容请求也失败: ${errorMessage(fallbackError)}${fallbackStatus}`); throw fallbackError; } } return (payload.results || []).flatMap((item) => { const row = item as Record<string, unknown>; return typeof row.url === "string" ? [{ url: row.url, title: typeof row.title === "string" ? row.title : undefined, content: typeof row.content === "string" ? row.content : undefined }] : []; }); }) }); }
async function brave(query: string): Promise<Hit[]> { const key = process.env.BRAVE_SEARCH_API_KEY?.trim(); if (!key) { if (!warnedBraveKey) { console.warn("[警告] 未配置 Brave Search API Key，将跳过 Fallback"); warnedBraveKey = true; } return []; } const body = await requestJson(`https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}&count=10`, { accept: "application/json", "X-Subscription-Token": key }) as { web?: { results?: Array<{ url?: string; title?: string; description?: string }> } }; return (body.web?.results || []).flatMap((item) => typeof item.url === "string" ? [{ url: item.url, title: item.title, content: item.description }] : []); }
async function bing(query: string): Promise<Hit[]> { const key = process.env.BING_SEARCH_API_KEY?.trim(); if (!key) { if (!warnedBingKey) { console.warn("[警告] 未配置 Bing Search API Key，将跳过 Fallback"); warnedBingKey = true; } return []; } const body = await requestJson(`https://api.bing.microsoft.com/v7.0/search?q=${encodeURIComponent(query)}&count=10`, { accept: "application/json", "Ocp-Apim-Subscription-Key": key }) as { webPages?: { value?: Array<{ url?: string; name?: string; snippet?: string }> } }; return (body.webPages?.value || []).flatMap((item) => typeof item.url === "string" ? [{ url: item.url, title: item.name, content: item.snippet }] : []); }
async function searchWithFallback(query: string, urls: string[]): Promise<Hit[]> { let hits: Hit[] = []; try { hits = await searx(urls, query); } catch (error) { console.error(`[SearXNG] 搜索失败，原因: ${errorMessage(error)}`); } if (hits.length === 0) { console.log(`[Fallback] 触发 Brave/Bing 搜索... query=${query}`); if ((!process.env.BRAVE_SEARCH_API_KEY?.trim() || !process.env.BING_SEARCH_API_KEY?.trim()) && !warnedFallbackKeys) { console.warn("[警告] 未配置 Brave/Bing API Key，将跳过 Fallback"); warnedFallbackKeys = true; } for (const [name, provider] of [["Brave", brave], ["Bing", bing]] as const) { try { hits = await provider(query); if (hits.length) break; } catch (error) { console.error(`[Fallback] ${name} 搜索失败: ${errorMessage(error)}`); } } } return hits; }
async function readWhitelist(): Promise<WhitelistEntry[]> { try { const raw = JSON.parse(await readFile(WHITELIST, "utf8")) as Record<string, unknown>; const values = Array.isArray(raw.institutions) ? raw.institutions : Array.isArray(raw.organizations) ? raw.organizations : []; return values.flatMap((item): WhitelistEntry[] => { if (!item || typeof item !== "object") return []; const row = item as Record<string, unknown>; const officialDomain = typeof row.official_domain === "string" ? row.official_domain : typeof row.domain === "string" ? row.domain : ""; if (!officialDomain.trim()) return []; return [{ name: typeof row.name === "string" ? row.name : undefined, code: typeof row.code === "string" ? row.code : undefined, aliases: Array.isArray(row.aliases) ? row.aliases.filter((value): value is string => typeof value === "string") : [], officialDomain }]; }); } catch (error) { console.warn(`[白名单] 读取失败`, error); return []; } }
function whitelistMatch(org: Organization, whitelist: WhitelistEntry[]): WhitelistEntry | undefined { const keys = new Set([normalize(org.originalName), normalize(org.identifier)]); return whitelist.find((entry) => [entry.name, entry.code, ...entry.aliases].filter(Boolean).some((value) => keys.has(normalize(value as string)))); }
function whitelistResult(org: Organization, entry: WhitelistEntry): Result | null { const url = safeUrl(/^https?:\/\//i.test(entry.officialDomain) ? entry.officialDomain : `https://${entry.officialDomain}`); if (!url || excluded(url.hostname)) return null; return { name: org.identifier, status: "whitelist_match", checkedAt: new Date().toISOString(), official_domain: url.hostname.replace(/^www\./, ""), candidates: [], sources: [{ url: `${url.origin}/`, type: "whitelist_match" }] }; }
async function discover(org: Organization, urls: string[], whitelist: WhitelistEntry[]): Promise<Result> { const matched = whitelistMatch(org, whitelist); if (matched) { const result = whitelistResult(org, matched); if (result) return result; } const candidates: string[] = []; const aliases = [...(matched?.aliases || []), ...(org.identifier !== org.originalName ? [org.identifier] : [])]; const identity = { name: org.originalName, aliases }; for (const query of [`"${org.originalName}" official website`, `"${org.originalName}" homepage`]) { const hits = await searchWithFallback(query, urls); candidates.push(...hits.map((hit) => hit.url)); for (const hit of hits) { const url = safeUrl(hit.url); if (!url || excluded(url.hostname)) continue; try { if (!(await publicHost(url.hostname))) { console.warn(`[验证失败] 机构 ${org.originalName}, URL: ${hit.url}, 原因: DNS 解析到非公开地址`); continue; } } catch (error) { console.warn(`[验证失败] 机构 ${org.originalName}, URL: ${hit.url}, 原因: DNS 解析失败: ${errorMessage(error)}`); continue; } const verified = await homepageLimiter.run(() => verifyCandidateHomepage(hit.url, identity)); const looseVerified = verified || await homepageLimiter.run(() => verifyCandidateHomepage(hit.url, identity, { loose: true })); if (verified || looseVerified) return { name: org.identifier, status: "online_verified", checkedAt: new Date().toISOString(), official_domain: url.hostname.replace(/^www\./, ""), candidates: [...new Set(candidates)].slice(0, 8), sources: [{ url: `${url.origin}/`, type: "search" }] }; } } return { name: org.identifier, status: "unverified", checkedAt: new Date().toISOString(), official_domain: null, candidates: [...new Set(candidates)].slice(0, 8), sources: [] }; }
async function state(org: Organization, status: "success" | "failed"): Promise<void> { const now = new Date().toISOString(); await db().execute({ sql: "UPDATE organizations SET last_searched_at = ?, search_status = ?, updated_at = ? WHERE entity_id = ? OR slug = ? OR name = ?", args: [now, status, now, org.identifier, org.identifier, org.originalName] }); }
async function progress(total: number, processed: number, success: number, current: string | null): Promise<void> { await mkdir(dirname(PROGRESS), { recursive: true }); await writeFile(PROGRESS, `${JSON.stringify({ taskId: `discover_${process.pid}`, total, processed, success, failed: processed - success, currentInstitution: current, status: processed === total ? "completed" : "running", lastUpdated: new Date().toISOString() }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); }
async function main(): Promise<void> { const args = minimist(process.argv.slice(2), { string: ["limit"], default: { limit: Infinity } }); const raw = JSON.parse(await readFile(INPUT, "utf8")) as unknown[]; const organizations = raw.map((item) => typeof item === "string" ? { originalName: item, identifier: item } : { originalName: clean(String((item as Record<string, unknown>).name || (item as Record<string, unknown>).code || "")), identifier: clean(String((item as Record<string, unknown>).code || (item as Record<string, unknown>).name || "")) }).filter((item) => item.originalName).slice(0, Number(args.limit) || undefined); const whitelist = await readWhitelist(); const configuredUrls = SEARXNG.length ? SEARXNG : ["http://localhost:8080"]; const pool = await checkSearxngPool(configuredUrls); if (pool.failed.length) console.warn(`[SearXNG] 健康检查失败: ${pool.failed.map((item) => `${item.url} (${item.reason})`).join(", ")}`); const urls = pool.healthyUrls.length ? pool.healthyUrls : configuredUrls; let processed = 0; let success = 0; const results: Result[] = []; for (const org of organizations) { let result: Result; try { result = await discover(org, urls, whitelist); } catch (error) { result = { name: org.identifier, status: "error", checkedAt: new Date().toISOString(), official_domain: null, candidates: [], sources: [], error: String(error) }; console.error(`[发现失败] 机构 ${org.originalName}: ${errorMessage(error)}`); } results.push(result); processed += 1; if (result.status === "online_verified" || result.status === "whitelist_match") success += 1; await state(org, result.status === "online_verified" || result.status === "whitelist_match" ? "success" : "failed"); await progress(organizations.length, processed, success, org.originalName); if (processed % 10 === 0) logActiveSockets(`discover ${processed}/${organizations.length}`); } await mkdir(dirname(OUTPUT), { recursive: true }); await writeFile(OUTPUT, `${JSON.stringify({ schemaVersion: "organization-sources-secure/v1", generatedAt: new Date().toISOString(), organizations: results }, null, 2)}\n`, { mode: 0o600 }); dbClient?.close(); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
