"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

type EventItem = { id: string; organizationId: string; organizationName: string; organizationSlug: string; description: string; eventDate: string | null; category: "news" | "announcement" | "research" | "other"; sourceUrl: string | null; sourceName: string | null };
type Insights = { totalOrganizations: number; totalEvents: number; recentEvents: EventItem[]; eventsByCategory: Record<"news" | "announcement" | "research" | "other", EventItem[]>; activeWatchEvents: EventItem[]; passiveWatchEvents: EventItem[]; domainStats: Array<{ domain: string; count: number }> };
function dateLabel(value: string | null) { if (!value) return "近期"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "近期" : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit" }).format(date).replace("/", "-"); }
function shortText(value: string) { return value.length > 80 ? `${value.slice(0, 80)}…` : value; }
function EventRow({ event, timeline = false }: { event: EventItem; timeline?: boolean }) { const router = useRouter(); const goToEvent = () => router.push(`/events/${event.id}`); return <article className={`group cursor-pointer border-b border-[var(--line)] bg-white px-4 py-4 transition-all hover:bg-[var(--teal-soft)] hover:shadow-lg last:border-0 ${timeline ? "grid gap-3 sm:grid-cols-[72px_minmax(0,1fr)_180px] sm:items-start" : ""}`} role="link" tabIndex={0} onClick={goToEvent} onKeyDown={(keyboardEvent) => { if (keyboardEvent.key === "Enter" || keyboardEvent.key === " ") { keyboardEvent.preventDefault(); goToEvent(); } }}><p className="shrink-0 font-mono text-[11px] font-semibold text-[var(--coral)]">{dateLabel(event.eventDate)}</p><div className="min-w-0"><Link className="block rounded-sm hover:bg-[var(--teal-soft)]" href={`/events/${event.id}`} onClick={(clickEvent) => clickEvent.stopPropagation()}><p className="text-sm leading-6 text-[var(--ink)]">{shortText(event.description)}</p></Link><div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-slate-400"><span className="border border-slate-200 px-2 py-0.5">{event.category === "announcement" ? "公告" : event.category === "research" ? "研究" : event.category === "news" ? "News" : "Other"}</span>{event.sourceUrl ? <><a className="text-[var(--teal)] hover:underline" href={event.sourceUrl} target="_blank" rel="noreferrer" onClick={(clickEvent) => clickEvent.stopPropagation()}>原文 ↗</a><a className="text-[var(--teal)] hover:underline" href={event.sourceUrl} target="_blank" rel="noreferrer" onClick={(clickEvent) => clickEvent.stopPropagation()}>来源：{event.sourceName || "未知"} ↗</a></> : <span>暂无来源</span>}</div></div><Link className="truncate text-xs font-semibold text-[var(--teal)] hover:underline sm:text-right" href={`/organizations/${event.organizationSlug}`} onClick={(clickEvent) => clickEvent.stopPropagation()}>{event.organizationName} ↗</Link></article>; }
export default function HomePage() {
  const [data, setData] = useState<Insights | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [tab, setTab] = useState<"news" | "announcement" | "research">("news");
  useEffect(() => { fetch("/api/insights", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || "无法加载工作台数据"); setData(payload.data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "无法加载工作台数据")).finally(() => setLoading(false)); }, []);
  const format = (value?: number) => value == null ? "--" : new Intl.NumberFormat("zh-CN").format(value); const labels = { news: "新闻动态 (News)", announcement: "官方公告 (Announcements)", research: "研究报告 (Research)" } as const; const maxDomain = Math.max(...(data?.domainStats.map((item) => item.count) || [1]));
  return <main className="space-y-8"><section className="flex flex-col justify-between gap-5 border-b border-[var(--line)] pb-7 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--teal)]">Research overview</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[var(--ink)]">机构情报工作台</h1><p className="mt-2 text-sm text-[var(--muted)]">从时间、类别、关注方式和机构域名多个维度审阅公开信号。</p></div><Link className="bg-[var(--ink)] px-4 py-3 text-sm font-semibold text-white hover:bg-[#263758]" href="/events">查看全部事件 →</Link></section>{error ? <section className="border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</section> : null}<section className="grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2"><Stat label="机构总数" value={format(data?.totalOrganizations)} /><Stat label="事件总数" value={format(data?.totalEvents)} /></section><section><SectionHeading eyebrow="Latest intelligence" title="最新动态 (Latest Intelligence)" /><div className="border-y border-[var(--line)]">{loading ? <Loading /> : data?.recentEvents.length ? data.recentEvents.map((event) => <EventRow event={event} timeline key={event.id} />) : <Empty />}</div><Link className="mt-4 inline-flex text-sm font-semibold text-[var(--teal)] hover:underline" href="/events">查看更多事件 →</Link></section><section><SectionHeading eyebrow="Categories" title="按类别分类" /><div className="flex gap-1 overflow-x-auto border-b border-[var(--line)]">{(Object.keys(labels) as Array<keyof typeof labels>).map((key) => <button className={`px-4 py-3 text-sm font-semibold ${tab === key ? "border-b-2 border-[var(--teal)] text-[var(--teal)]" : "text-slate-500"}`} key={key} onClick={() => setTab(key)}>{labels[key]}</button>)}</div><div className="border-b border-[var(--line)]">{loading ? <Loading /> : data?.eventsByCategory[tab]?.length ? data.eventsByCategory[tab].slice(0, 8).map((event) => <EventRow event={event} key={event.id} />) : <Empty />}</div></section><section><SectionHeading eyebrow="Watch modes" title="关注类型对比" /><div className="grid gap-6 lg:grid-cols-2"><WatchPanel title="主动监测 (Active Watch)" detail="官网抓取" events={data?.activeWatchEvents || []} /><WatchPanel title="被动发现 (Passive Discovery)" detail="SearXNG 外部新闻" events={data?.passiveWatchEvents || []} /></div></section><section><SectionHeading eyebrow="Domain distribution" title="领域分布" /><div className="border-y border-[var(--line)] bg-white p-5"><div className="space-y-4">{loading ? <Loading /> : data?.domainStats.length ? data.domainStats.slice(0, 12).map((item) => <div key={item.domain}><div className="flex justify-between text-xs"><span className="font-mono text-[var(--ink)]">{item.domain}</span><span className="text-slate-500">{item.count}</span></div><div className="mt-2 h-2 bg-slate-100"><div className="h-2 bg-[var(--teal)]" style={{ width: `${Math.max(4, (item.count / maxDomain) * 100)}%` }} /></div></div>) : <Empty />}</div></div></section></main>;
}
function Stat({ label, value }: { label: string; value: string }) { return <article className="bg-white p-5"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-3 text-3xl font-semibold text-[var(--ink)]">{value}</p></article>; }
function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-4 border-b border-[var(--line)] pb-3"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--teal)]">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold text-[var(--ink)]">{title}</h2></div>; }
function WatchPanel({ title, detail, events }: { title: string; detail: string; events: EventItem[] }) { return <div><div className="mb-3 flex items-end justify-between"><h3 className="font-semibold text-[var(--ink)]">{title}</h3><span className="text-xs text-slate-400">{detail} · {events.length} 条</span></div><div className="border-y border-[var(--line)]">{events.length ? events.map((event) => <EventRow event={event} key={event.id} />) : <Empty />}</div></div>; }
function Loading() { return <div className="space-y-3 bg-white p-5"><div className="h-3 w-2/5 animate-pulse bg-slate-100" /><div className="h-3 w-4/5 animate-pulse bg-slate-100" /></div>; }
function Empty() { return <div className="bg-white px-5 py-8 text-center text-sm text-slate-400">暂无事件数据</div>; }
