#!/usr/bin/env npx tsx
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { and, eq, isNotNull, sql } from "drizzle-orm";
import { events, organizations } from "../../db/schema";
import { fetchExternalUrl } from "../../lib/security-url";
import { chatCompletion } from "../../lib/llm-client";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const DB_PATH = process.env.LOCAL_SQLITE_PATH?.trim() || resolve(ROOT, ".local/d1.sqlite");
const PROGRESS = resolve(ROOT, "data/news_search_progress.json");
const SEARXNG = (process.env.SEARXNG_URL?.trim() || "http://localhost:8080").replace(/\/+$/, "");
const MIN_SCORE = 6;
type EventType = "report" | "partnership" | "personnel" | "policy" | "research" | "award" | "other";
type Organization = { entityId: string; name: string; officialDomain: string | null; sources: string | null; lastEventSearchedAt: string | null; eventSearchStatus: "pending" | "success" | "failed" };
type Candidate = { title: string; url: string; summary: string; eventDate: string; sourceName: string; relevanceScore?: number; eventType?: EventType };
const text = (v: unknown): string => typeof v === "string" ? v.replace(/\s+/g, " ").trim() : "";
const canonical = (v: string): string | null => { try { const u = new URL(v); if (!["http:", "https:"].includes(u.protocol)) return null; u.hash = ""; return u.toString(); } catch { return null; } };
const host = (v: string): string => { try { return new URL(v).hostname.toLowerCase().replace(/^www\./, ""); } catch { return "unknown"; } };
const date = (v: string): string => { const m = v.match(/(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/); if (!m) return "unknown"; const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3])); return Number.isNaN(d.getTime()) ? "unknown" : d.toISOString().slice(0, 10); };
function saveProgress(processedIds: string[]): void { mkdirSync(dirname(PROGRESS), { recursive: true }); writeFileSync(PROGRESS, JSON.stringify({ processedIds, updatedAt: new Date().toISOString() }, null, 2)); }
async function search(organization: Organization): Promise<Candidate[]> { const url = new URL(`${SEARXNG}/search`); url.searchParams.set("q", `"${organization.name}" news`); url.searchParams.set("format", "json"); const response = await fetch(url, { headers: { accept: "application/json" }, signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw new Error(`SearXNG HTTP ${response.status}`); const payload = await response.json() as { results?: unknown[] }; return (payload.results || []).flatMap((item) => { const r = item as Record<string, unknown>; const u = typeof r.url === "string" ? canonical(r.url) : null; if (!u) return []; return [{ title: text(r.title) || u, url: u, summary: text(r.content), eventDate: date(`${text(r.publishedDate)} ${u}`), sourceName: host(u) }]; }).slice(0, 10); }
async function homepage(organization: Organization): Promise<Candidate[]> { if (!organization.officialDomain) return []; const base = canonical(/^https?:\/\//i.test(organization.officialDomain) ? organization.officialDomain : `https://${organization.officialDomain}`); if (!base) return []; const response = await fetchExternalUrl(base, { timeoutMs: 10_000 }); if (!response.ok) return []; const html = await response.text(); return [...html.matchAll(/href=["']([^"']+)["'][^>]*>([^<]*(?:news|event|announcement)[^<]*)</gi)].slice(0, 10).flatMap((m) => { const u = canonical(new URL(m[1], base).toString()); return u ? [{ title: text(m[2]) || u, url: u, summary: text(m[2]), eventDate: date(u), sourceName: host(u) }] : []; }); }
function parseArray(value: string): unknown[] { const start = value.indexOf("["); const end = value.lastIndexOf("]"); if (start < 0 || end <= start) return []; try { const parsed = JSON.parse(value.slice(start, end + 1)); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
async function extractEvents(organization: Organization, candidates: Candidate[]): Promise<Candidate[]> { if (!candidates.length) return []; const response = await chatCompletion("Extract events as JSON array only. Include url,title,summary,event_date,event_type,relevance_score (1-10).", JSON.stringify({ organization: organization.name, candidates }), { timeout: 120_000 }); const byUrl = new Map(candidates.map((c) => [c.url, c])); return parseArray(response).flatMap((item) => { const r = item as Record<string, unknown>; const u = typeof r.url === "string" ? canonical(r.url) : null; const score = Number(r.relevance_score); const c = u ? byUrl.get(u) : undefined; if (!u || !c || !Number.isInteger(score) || score < 1 || score > 10) return []; const types: EventType[] = ["report", "partnership", "personnel", "policy", "research", "award", "other"]; return [{ ...c, url: u, title: text(r.title) || c.title, summary: text(r.summary) || c.summary, eventDate: text(r.event_date) || c.eventDate, eventType: types.includes(r.event_type as EventType) ? r.event_type as EventType : "other", relevanceScore: score }]; }); }
function filterQualityAndDuplicates(results: Candidate[]): Candidate[] { const out: Candidate[] = []; const normalize = (v: string) => v.toLocaleLowerCase().replace(/[\s\p{P}\p{S}_]+/gu, ""); for (const item of results.filter((r) => (r.relevanceScore || 0) >= MIN_SCORE).sort((a, b) => (b.relevanceScore || 0) - (a.relevanceScore || 0))) { const a = normalize(item.title); if (out.some((x) => normalize(x.title).includes(a) || a.includes(normalize(x.title)))) continue; out.push(item); } return out.slice(0, 10); }
async function main(): Promise<void> { const resume = process.argv.includes("--resume"); const completed = new Set<string>(resume && existsSync(PROGRESS) ? JSON.parse(readFileSync(PROGRESS, "utf8")).processedIds || [] : []); if (DB_PATH !== ":memory:") mkdirSync(dirname(DB_PATH), { recursive: true }); const client = createClient({ url: DB_PATH === ":memory:" ? "file::memory:" : `file:${DB_PATH}` }); const db = drizzle(client); try { const all = await db.select({ entityId: organizations.entityId, name: organizations.name, officialDomain: organizations.websiteUrl, sources: organizations.sources, lastEventSearchedAt: organizations.lastEventSearchedAt, eventSearchStatus: organizations.eventSearchStatus }).from(organizations).where(and(isNotNull(organizations.websiteUrl), sql`length(trim(${organizations.websiteUrl})) > 0`)).all() as Organization[]; const existing = new Set((await db.select({ sourceUrl: events.sourceUrl }).from(events).all()).map((x) => x.sourceUrl ? canonical(x.sourceUrl) : null).filter((x): x is string => Boolean(x))); let processed = 0; for (const org of all.filter((x) => !completed.has(x.entityId))) { let status: "success" | "failed" = "success"; try { const raw = [...await search(org), ...(await homepage(org))]; const candidates = [...new Map(raw.map((x) => [x.url, x])).values()]; // 融合逻辑：B 抓取后调用 A 的 LLM 抽取和质量去重，再写入数据库。
        const cleaned = filterQualityAndDuplicates(await extractEvents(org, candidates)); for (const item of cleaned) { if (existing.has(item.url)) continue; await db.insert(events).values({ id: randomUUID(), organizationId: org.entityId, eventDate: item.eventDate, eventType: item.eventType || "other", relevanceScore: item.relevanceScore, title: item.title, summary: item.summary || item.title, sourceUrl: item.url, sourceName: item.sourceName }).run(); existing.add(item.url); } } catch (error) { status = "failed"; console.error(`[news:${org.name}] ${String(error)}`); } const now = new Date().toISOString(); await db.update(organizations).set({ lastEventSearchedAt: now, eventSearchStatus: status, updatedAt: now }).where(eq(organizations.entityId, org.entityId)).run(); completed.add(org.entityId); processed += 1; saveProgress([...completed]); console.log(`[progress] ${processed}/${all.length}`); } } finally { client.close(); } }
main().catch((error) => { console.error(error); process.exitCode = 1; });
